monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Elgato_Systems_Elgato_Wave_3_BS45J1A00138-00"
      }
    ]
    actions = {
      update-props = {
		# Uncouples software mixer from hardware mixer
        api.alsa.use-acp = false
        # Prevents the Elgato from hanging on a reboot/sleep cycle
        session.suspend-on-idle = false
      }
    }
  }
]
